# Generated by Django 2.2.17 on 2021-01-09 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import timecards.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payType', models.CharField(choices=[('0', 'Regular'), ('1', 'EPL'), ('2', 'Vacation'), ('3', 'Sick')], default='VAC', max_length=32)),
                ('startTime', models.DateField(default=timecards.models.start_time)),
                ('endTime', models.DateField(default=timecards.models.end_time)),
                ('currentTime', models.DateField(default=timecards.models.current_time)),
                ('monTime', models.FloatField(blank=True, null=True)),
                ('tueTime', models.FloatField(blank=True, null=True)),
                ('wedTime', models.FloatField(blank=True, null=True)),
                ('thuTime', models.FloatField(blank=True, null=True)),
                ('friTime', models.FloatField(blank=True, null=True)),
                ('satTime', models.FloatField(blank=True, null=True)),
                ('sunTime', models.FloatField(blank=True, null=True)),
                ('totalTime', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(default='csmel', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payrate', models.FloatField(blank=True, default=22.0, null=True)),
                ('user', models.ForeignKey(default='csmel', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollTotal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.IntegerField(unique=True)),
                ('paycode', models.CharField(default='Regular', max_length=32)),
                ('total_reg_hours', models.FloatField(default=0.0)),
                ('total_reg_hours_amount', models.FloatField(default=0.0)),
                ('rate_overtime', models.FloatField(default=0.0)),
                ('total_overtime_hours', models.FloatField(default=0.0)),
                ('total_overtime_amount', models.FloatField(default=0.0)),
                ('begin_bal_epl', models.FloatField(default=24)),
                ('current_week_epl', models.FloatField(default=0.0)),
                ('end_bal_epl', models.FloatField(default=0.0)),
                ('begin_bal_vac', models.FloatField(default=500)),
                ('current_week_vac', models.FloatField(default=0.0)),
                ('end_bal_vac', models.FloatField(default=0.0)),
                ('payroll_EPL', models.ForeignKey(blank=True, limit_choices_to={'payType': '1'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_EPL', to='timecards.Payroll')),
                ('payroll_REG', models.ForeignKey(blank=True, limit_choices_to={'payType': '0'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_REG', to='timecards.Payroll')),
                ('payroll_VAC', models.ForeignKey(blank=True, limit_choices_to={'payType': '2'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_VAC', to='timecards.Payroll')),
                ('rate', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='timecards.PayrollProfile')),
            ],
        ),
    ]
