# Generated by Django 2.2.17 on 2021-01-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecards', '0002_remove_payrolltotal_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolltotal',
            name='identifier',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
