# Generated by Django 2.2.17 on 2021-01-09 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timecards', '0003_payrolltotal_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolltotal',
            name='begin_bal_sic',
            field=models.FloatField(default=500),
        ),
        migrations.AddField(
            model_name='payrolltotal',
            name='current_week_sic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payrolltotal',
            name='end_bal_sic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='payrolltotal',
            name='payroll_SIC',
            field=models.ForeignKey(blank=True, limit_choices_to={'payType': '2'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_SIC', to='timecards.Payroll'),
        ),
    ]
