# Generated by Django 2.2.17 on 2021-01-09 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timecards', '0004_auto_20210109_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolltotal',
            name='payroll_EPL',
            field=models.ForeignKey(blank=True, limit_choices_to={'payType': '1'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_EPL', to='timecards.Payroll'),
        ),
        migrations.AlterField(
            model_name='payrolltotal',
            name='payroll_SIC',
            field=models.ForeignKey(blank=True, limit_choices_to={'payType': '2'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_SIC', to='timecards.Payroll'),
        ),
        migrations.AlterField(
            model_name='payrolltotal',
            name='payroll_VAC',
            field=models.ForeignKey(blank=True, limit_choices_to={'payType': '2'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_VAC', to='timecards.Payroll'),
        ),
        migrations.AlterField(
            model_name='payrolltotal',
            name='rate',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate', to='timecards.PayrollProfile'),
        ),
    ]
