# Generated by Django 2.2.17 on 2021-01-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timecards', '0005_auto_20210109_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolltotal',
            name='start_bal_epl',
            field=models.FloatField(default=24),
        ),
        migrations.AddField(
            model_name='payrolltotal',
            name='start_bal_sic',
            field=models.FloatField(default=500),
        ),
        migrations.AddField(
            model_name='payrolltotal',
            name='start_bal_vac',
            field=models.FloatField(default=500),
        ),
        migrations.AlterField(
            model_name='payrolltotal',
            name='begin_bal_epl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payrolltotal',
            name='begin_bal_sic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payrolltotal',
            name='begin_bal_vac',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='payrolltotal',
            name='payroll_SIC',
            field=models.ForeignKey(blank=True, limit_choices_to={'payType': '3'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_SIC', to='timecards.Payroll'),
        ),
    ]
