# Generated by Django 2.2.17 on 2021-01-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecards', '0006_auto_20210110_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrolltotal',
            name='id',
        ),
        migrations.AlterField(
            model_name='payrolltotal',
            name='identifier',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
