# Generated by Django 2.2.17 on 2021-01-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecards', '0008_auto_20210113_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrolltotal',
            name='identifier',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
