# Generated by Django 2.2.17 on 2021-01-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timecards', '0009_payrolltotal_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollprofile',
            name='eplBank',
            field=models.FloatField(blank=True, default=24.0, null=True),
        ),
        migrations.AddField(
            model_name='payrollprofile',
            name='sicBank',
            field=models.FloatField(blank=True, default=24.0, null=True),
        ),
        migrations.AddField(
            model_name='payrollprofile',
            name='vacBank',
            field=models.FloatField(blank=True, default=500.0, null=True),
        ),
    ]
