# Generated by Django 2.2.17 on 2020-11-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecomment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='slug',
            field=models.SlugField(),
        ),
    ]
