# Generated by Django 2.2.17 on 2020-11-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201121_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='userliked',
        ),
        migrations.AddField(
            model_name='article',
            name='usrliked',
            field=models.TextField(default='hi', max_length=100),
        ),
    ]
