# Generated by Django 2.2.17 on 2020-12-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201126_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='userliked',
            field=models.TextField(max_length=100),
        ),
    ]
