# Generated by Django 2.2.17 on 2020-11-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201121_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='likess',
            new_name='likes',
        ),
    ]
