# Generated by Django 2.2.17 on 2020-11-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20201122_0724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='likes',
            new_name='like',
        ),
    ]
