# Generated by Django 2.2.17 on 2020-12-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20201210_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='userliked',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
