# Generated by Django 2.2.17 on 2020-11-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20201122_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='usrliked',
            new_name='userliked',
        ),
    ]
