# Generated by Django 3.0.8 on 2020-08-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilenew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfileNew',
        ),
    ]
