# Generated by Django 2.2.17 on 2020-12-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201213_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='djangoLogo.jpg', upload_to='media/'),
        ),
    ]
