# Generated by Django 2.2.17 on 2020-12-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20201213_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=0.00023573785950023574, upload_to=''),
            preserve_default=False,
        ),
    ]
